<!DOCTYPE html>
<html>
<head>
	<title>Jquery slideshow generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Jquery slideshow" />
	
	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->

</head>
<body style="background-color:#d7d7d7;margin:auto">
	
	<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
		<li><a href="http://www.allbreedrescuevt.com/animals/detail?AnimalID=5736243" target="_blank"><img src="data1/images/16327525_500x400.jpg" alt="Celine" title="Celine" id="wows1_0"/></a></li>
		<li><a href="http://www.allbreedrescuevt.com/animals/detail?AnimalID=6001152" target="_blank"><img src="data1/images/17698602_500x333.jpg" alt="Akay" title="Akay" id="wows1_1"/></a></li>
		<li><a href="http://www.allbreedrescuevt.com/animals/detail?AnimalID=5998611" target="_blank"><img src="data1/images/17769304_500x332.jpg" alt="Dolly" title="Dolly" id="wows1_2"/></a></li>
		<li><a href="http://www.allbreedrescuevt.com/animals/detail?AnimalID=5583339" target="_blank"><img src="data1/images/20291698_500x335.jpg" alt="Seth" title="Seth" id="wows1_3"/></a></li>
		<li><a href="http://www.allbreedrescuevt.com/animals/detail?AnimalID=7615737" target="_blank"><img src="data1/images/22657273_500x281.jpg" alt="Roxy" title="Roxy" id="wows1_4"/></a></li>
		<li><a href="http://www.allbreedrescuevt.com/animals/detail?AnimalID=7680455" target="_blank"><img src="data1/images/22942161_500x375.jpg" alt="Annie" title="Annie" id="wows1_5"/></a></li>
		<li><a href="http://www.allbreedrescuevt.com/animals/detail?AnimalID=7745907" target="_blank"><img src="data1/images/23233140_500x375.jpg" alt="Spyder" title="Spyder" id="wows1_6"/></a></li>
		<li><a href="http://www.allbreedrescuevt.com/animals/detail?AnimalID=7746232" target="_blank"><img src="data1/images/23234089_500x375.jpg" alt="Strudel" title="Strudel" id="wows1_7"/></a></li>
		<li><img src="data1/images/23642201_500x375.jpg" alt="23642201_500x375" title="23642201_500x375" id="wows1_8"/></li>
		<li><a href="http://www.allbreedrescuevt.com/animals/detail?AnimalID=7945140" target="_blank"><img src="data1/images/23806953_500x375.jpg" alt="Sparky" title="Sparky" id="wows1_9"/></a></li>
		<li><img src="data1/images/23806962_500x331.jpg" alt="Brindle" title="Brindle" id="wows1_10"/></li>
		<li><img src="data1/images/23820153_500x333.jpg" alt="Tuesday" title="Tuesday" id="wows1_11"/></li>
		<li><img src="data1/images/23820420_500x333.jpg" alt="Wednesday" title="Wednesday" id="wows1_12"/></li>
		<li><a href="http://www.allbreedrescuevt.com/animals/detail?AnimalID=7945430" target="_blank"><img src="data1/images/23835639_500x375.jpg" alt="Agnes" title="Agnes" id="wows1_13"/></a></li>
		<li><a href="http://www.allbreedrescuevt.com/animals/detail?AnimalID=7462894" target="_blank"><img src="data1/images/22156841_480x640.jpg" alt="Bailey" title="Bailey" id="wows1_14"/></a></li>
		<li><img src="data1/images/19405750_500x740.jpg" alt="Ray Charles" title="Ray Charles" id="wows1_15"/></li>
		<li><img src="data1/images/20744551_500x741.jpg" alt="Megan" title="Megan" id="wows1_16"/></li>
		<li><img src="data1/images/21535664_424x436.jpg" alt="Cocoa" title="Cocoa" id="wows1_17"/></li>
		<li><a href="http://wowslider.com"><img src="data1/images/22758764_500x370.jpg" alt="wowslider" title="Honey" id="wows1_18"/></a></li>
		<li><img src="data1/images/23820453_500x750.jpg" alt="Sophie" title="Sophie" id="wows1_19"/></li>
	</ul></div>
	<div class="ws_bullets"><div>
		<a href="#" title="Celine"><img src="data1/tooltips/16327525_500x400.jpg" alt="Celine"/>1</a>
		<a href="#" title="Akay"><img src="data1/tooltips/17698602_500x333.jpg" alt="Akay"/>2</a>
		<a href="#" title="Dolly"><img src="data1/tooltips/17769304_500x332.jpg" alt="Dolly"/>3</a>
		<a href="#" title="Seth"><img src="data1/tooltips/20291698_500x335.jpg" alt="Seth"/>4</a>
		<a href="#" title="Roxy"><img src="data1/tooltips/22657273_500x281.jpg" alt="Roxy"/>5</a>
		<a href="#" title="Annie"><img src="data1/tooltips/22942161_500x375.jpg" alt="Annie"/>6</a>
		<a href="#" title="Spyder"><img src="data1/tooltips/23233140_500x375.jpg" alt="Spyder"/>7</a>
		<a href="#" title="Strudel"><img src="data1/tooltips/23234089_500x375.jpg" alt="Strudel"/>8</a>
		<a href="#" title="23642201_500x375"><img src="data1/tooltips/23642201_500x375.jpg" alt="23642201_500x375"/>9</a>
		<a href="#" title="Sparky"><img src="data1/tooltips/23806953_500x375.jpg" alt="Sparky"/>10</a>
		<a href="#" title="Brindle"><img src="data1/tooltips/23806962_500x331.jpg" alt="Brindle"/>11</a>
		<a href="#" title="Tuesday"><img src="data1/tooltips/23820153_500x333.jpg" alt="Tuesday"/>12</a>
		<a href="#" title="Wednesday"><img src="data1/tooltips/23820420_500x333.jpg" alt="Wednesday"/>13</a>
		<a href="#" title="Agnes"><img src="data1/tooltips/23835639_500x375.jpg" alt="Agnes"/>14</a>
		<a href="#" title="Bailey"><img src="data1/tooltips/22156841_480x640.jpg" alt="Bailey"/>15</a>
		<a href="#" title="Ray Charles"><img src="data1/tooltips/19405750_500x740.jpg" alt="Ray Charles"/>16</a>
		<a href="#" title="Megan"><img src="data1/tooltips/20744551_500x741.jpg" alt="Megan"/>17</a>
		<a href="#" title="Cocoa"><img src="data1/tooltips/21535664_424x436.jpg" alt="Cocoa"/>18</a>
		<a href="#" title="Honey"><img src="data1/tooltips/22758764_500x370.jpg" alt="Honey"/>19</a>
		<a href="#" title="Sophie"><img src="data1/tooltips/23820453_500x750.jpg" alt="Sophie"/>20</a>
	</div></div><span class="wsl"><a href="http://wowslider.com/vs">jquery slideshow</a> by WOWSlider.com v7.2m</span>
	<div class="ws_shadow"></div>
	</div>	
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->

</body>
</html>